name: Andrew's Training Train
description: Training hard and bringing you along for the ride
meta_description: "Andrew's Training Train"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://duensing.co'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Andrew Duensing'
